### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by ivxiaohangvi** [StarWishsama/SlimefunBlackList#1]
游戏版本:1.15.2
服务端版本:paper137
cscorelib版本:83
粘液科技版本:汉化版Nightly 每夜版 200315
https://github.com/StarWishsama/Slimefun4/releases/download/v4.2-200315/Slimefun-v4.2-NIGHTLY-200315.jar
报错信息:
[新建文本文档.txt](https://github.com/StarWishsama/SlimefunBlackList/files/4341097/default.txt)

所有功能都没用

**Comment by ivxiaohangvi** [comment]
[17:28:22 INFO]: [SlimefunBlackList] 已检测到前置 Slimefun, 正在启用...
[17:28:22 ERROR]: Error occurred while enabling SlimefunBlackList v1.0.1-RELEASE (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at io.github.starwishsama.slimefunblacklist.SlimefunBlackList.onEnable(SlimefunBlackList.java:35) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-137]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-137]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-137]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-137]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-137]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-137]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-137]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-137]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.bukkit.MetricsLite.<clinit>(MetricsLite.java:43) ~[?:?]
        ... 10 more
